// <auto-generated />
using System;
using ControleOKR.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleOKR.Repository.Migrations
{
    [DbContext(typeof(ControleOKRContext))]
    [Migration("20210406005043_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("ControleOKR.Domain.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeEmpresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropostaValor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ControleOKR.Domain.Objetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataParaMeta")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinicaoObjetivo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PorcentagemRealizadaDaMeta")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Objetivos");
                });

            modelBuilder.Entity("ControleOKR.Domain.ResultadoChave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoResultadoChave")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObjetivoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reponsavel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("ResultadosChaves");
                });

            modelBuilder.Entity("ControleOKR.Domain.ResultadoChaveAtividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoAtividade")
                        .HasColumnType("TEXT");

                    b.Property<int>("PesoDaAtividade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultadoChaveId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalConcluidoDaAtividade")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ResultadoChaveId");

                    b.ToTable("ResultadosChavesAtividades");
                });

            modelBuilder.Entity("ControleOKR.Domain.Objetivo", b =>
                {
                    b.HasOne("ControleOKR.Domain.Empresa", "Empresa")
                        .WithMany("Objetivos")
                        .HasForeignKey("EmpresaId");
                });

            modelBuilder.Entity("ControleOKR.Domain.ResultadoChave", b =>
                {
                    b.HasOne("ControleOKR.Domain.Objetivo", "Objetivo")
                        .WithMany()
                        .HasForeignKey("ObjetivoId");
                });

            modelBuilder.Entity("ControleOKR.Domain.ResultadoChaveAtividade", b =>
                {
                    b.HasOne("ControleOKR.Domain.ResultadoChave", "ResultadoChave")
                        .WithMany()
                        .HasForeignKey("ResultadoChaveId");
                });
#pragma warning restore 612, 618
        }
    }
}
