// <auto-generated />
using System;
using ControleOKR.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleOKR.Repository.Migrations
{
    [DbContext(typeof(ControleOKRContext))]
    partial class ControleOKRContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("ControleOKR.Domain.ControleDeOKR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObjetivoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ControleDeOKRs");
                });

            modelBuilder.Entity("ControleOKR.Domain.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ControleDeOKRId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeEmpresa")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObjetivoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropostaValor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ControleDeOKRId");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ControleOKR.Domain.Objetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ControleDeOKRId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinicaoObjetivo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlanejamentoMetaObjetivosId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultadoChaveId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ControleDeOKRId");

                    b.ToTable("Objetivos");
                });

            modelBuilder.Entity("ControleOKR.Domain.PlanejamentoMetaObjetivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObjetivoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Porcentagem")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("PlanejamentoMetasObjetivos");
                });

            modelBuilder.Entity("ControleOKR.Domain.ResultadoChave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoResultadoChave")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObjetivoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reponsavel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResultadoChaveAtividadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("ResultadosChaves");
                });

            modelBuilder.Entity("ControleOKR.Domain.ResultadoChaveAtividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoAtividade")
                        .HasColumnType("TEXT");

                    b.Property<int>("PesoDaAtividade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultadoChaveId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalConcluidoDaAtividade")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ResultadoChaveId");

                    b.ToTable("ResultadosChavesAtividades");
                });

            modelBuilder.Entity("ControleOKR.Domain.Empresa", b =>
                {
                    b.HasOne("ControleOKR.Domain.ControleDeOKR", null)
                        .WithMany("Empresas")
                        .HasForeignKey("ControleDeOKRId");

                    b.HasOne("ControleOKR.Domain.Objetivo", "Objetivos")
                        .WithMany()
                        .HasForeignKey("ObjetivoId");
                });

            modelBuilder.Entity("ControleOKR.Domain.Objetivo", b =>
                {
                    b.HasOne("ControleOKR.Domain.ControleDeOKR", null)
                        .WithMany("Objetivos")
                        .HasForeignKey("ControleDeOKRId");
                });

            modelBuilder.Entity("ControleOKR.Domain.PlanejamentoMetaObjetivos", b =>
                {
                    b.HasOne("ControleOKR.Domain.Objetivo", null)
                        .WithMany("PlanejamentoMetas")
                        .HasForeignKey("ObjetivoId");
                });

            modelBuilder.Entity("ControleOKR.Domain.ResultadoChave", b =>
                {
                    b.HasOne("ControleOKR.Domain.Objetivo", null)
                        .WithMany("ResultadosChaves")
                        .HasForeignKey("ObjetivoId");
                });

            modelBuilder.Entity("ControleOKR.Domain.ResultadoChaveAtividade", b =>
                {
                    b.HasOne("ControleOKR.Domain.ResultadoChave", null)
                        .WithMany("AtividadesResultadoChave")
                        .HasForeignKey("ResultadoChaveId");
                });
#pragma warning restore 612, 618
        }
    }
}
